<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property string $word
 * @property Post $Post
 * 
 * @method integer getPostId()  Returns the current record's "post_id" value
 * @method string  getWord()    Returns the current record's "word" value
 * @method Post    getPost()    Returns the current record's "Post" value
 * @method Tag     setPostId()  Sets the current record's "post_id" value
 * @method Tag     setWord()    Sets the current record's "word" value
 * @method Tag     setPost()    Sets the current record's "Post" value
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('word', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}