<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $word
 * @property Doctrine_Collection $TagPost
 * 
 * @method string              getWord()    Returns the current record's "word" value
 * @method Doctrine_Collection getTagPost() Returns the current record's "TagPost" collection
 * @method Tag                 setWord()    Sets the current record's "word" value
 * @method Tag                 setTagPost() Sets the current record's "TagPost" collection
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('word', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TagPost', array(
             'local' => 'id',
             'foreign' => 'tag_id'));
    }
}