<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $title
 * @property string $content
 * 
 * @method string getName()    Returns the current record's "name" value
 * @method string getTitle()   Returns the current record's "title" value
 * @method string getContent() Returns the current record's "content" value
 * @method Page   setName()    Sets the current record's "name" value
 * @method Page   setTitle()   Sets the current record's "title" value
 * @method Page   setContent() Sets the current record's "content" value
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('title', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('content', 'string', 10240, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10240,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}