<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $content_path1
 * @property string $content_path2
 * @property integer $rating
 * @property Doctrine_Collection $Tag
 * @property Doctrine_Collection $Comment
 * 
 * @method string              getTitle()         Returns the current record's "title" value
 * @method string              getContentPath1()  Returns the current record's "content_path1" value
 * @method string              getContentPath2()  Returns the current record's "content_path2" value
 * @method integer             getRating()        Returns the current record's "rating" value
 * @method Doctrine_Collection getTag()           Returns the current record's "Tag" collection
 * @method Doctrine_Collection getComment()       Returns the current record's "Comment" collection
 * @method Post                setTitle()         Sets the current record's "title" value
 * @method Post                setContentPath1()  Sets the current record's "content_path1" value
 * @method Post                setContentPath2()  Sets the current record's "content_path2" value
 * @method Post                setRating()        Sets the current record's "rating" value
 * @method Post                setTag()           Sets the current record's "Tag" collection
 * @method Post                setComment()       Sets the current record's "Comment" collection
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content_path1', 'string', 1024, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1024,
             ));
        $this->hasColumn('content_path2', 'string', 10240, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10240,
             ));
        $this->hasColumn('rating', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tag', array(
             'local' => 'id',
             'foreign' => 'post_id'));

        $this->hasMany('Comment', array(
             'local' => 'id',
             'foreign' => 'post_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}