<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $login
 * @property string $password
 * @property string $email
 * @property Doctrine_Collection $Comment
 * 
 * @method string              getLogin()    Returns the current record's "login" value
 * @method string              getPassword() Returns the current record's "password" value
 * @method string              getEmail()    Returns the current record's "email" value
 * @method Doctrine_Collection getComment()  Returns the current record's "Comment" collection
 * @method User                setLogin()    Sets the current record's "login" value
 * @method User                setPassword() Sets the current record's "password" value
 * @method User                setEmail()    Sets the current record's "email" value
 * @method User                setComment()  Sets the current record's "Comment" collection
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('login', 'string', 16, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 16,
             ));
        $this->hasColumn('password', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 32,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Comment', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}