<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/01 17:33:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blog',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
