<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/09 12:53:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blog',
  'username' => 'adminblog',
  'password' => 'fMmPGYcTELm7MvWU',
  'name' => 'doctrine',
)),);
