<?php

/**
 * CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comment');
    }
    
    public function getCommentsPost($id_post)
    {
        $q = $this->createQuery('c')
             ->select('u.username, c.text')
             ->leftJoin('c.sfGuardUser u')   
             ->where('c.post_id = ?', $id_post)
             ->andWhere('c.sf_guard_user_id = u.id')
             ->orderBy('c.created_at DESC');
        
        return $q->execute();
    }
    
    public function getDateLastCommentUser($id_post, $id_user)
    {
        $q = $this->createQuery('c')
                        ->select('Unix_Timestamp(c.created_at) as datestamp')
                        ->where('c.sf_guard_user_id='.$id_user.' AND post_id='.$id_post)
                        ->orderBy('c.created_at DESC')
                        ->limit('1');
        $result = $q->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
        if( sizeof($result) == 0 )
            {return 0;}
        else
            {return $result;}
    }
}