<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Post extends BasePost
{
    
    public function getTagsPost($id_post)
    {
        $q = Doctrine_Query::create()
                ->select('t.*')
                ->from('Tag t')
                ->leftJoin('t.TagPost tp')
                ->andWhere('tp.post_id = ?', $id_post);
 
        return $q->execute();
    }
    
    public function getCountComment($id_post)
    {
        $q = Doctrine_Query::create()
                ->select('count(c.id) as countcomments')
                ->from('Comment c')
                ->where('c.post_id = ?', $id_post);
 
        return $q->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    }
    
    public static function getPopularPosts()
    {
        $q = Doctrine_Query::create()
                ->select('title')
                ->from('Post p')
                ->limit(sfConfig::get('app_max_post_on_popular'))
                ->orderBy('rating DESC');
 
        return $q->execute();
    }
    
    public function updateRating($post_id)
    {
        $q = Doctrine_Query::create()
                ->update('Post p')
                ->set('p.rating', 'p.rating + 1')
                ->where('p.id = ?', $post_id);
 
        return $q->execute();
    }


    public function getTags()
    {
        $tags = "";
        foreach($this->getTagsPost($this->getId()) as $tag)
        {
            $tags .= $tag->getWord().",";
        }
        return substr($tags, 0, -1);
    }
    
    
    public function setTags($strTags)
    {
        $tags = explode(",", $strTags);
        
        foreach($tags as $word)
        {
            $tag_id = 0;
            $post_id = $this->getId();
            $word = trim($word);
            $result = Doctrine_Core::getTable('Post')->findBy('word', $word);
            if($result->count() != 0)
            {
               $ins = Doctrine_Core::getTable('Tag')->create(array('word' => $word));
            }
            else
            {
                $tag_id = $result->getId();
            }
            $del = Doctrine_Query::create()
                    ->delete()
                    ->from('TafPost')
                    ->andWhere('post_id = '.$post_id)
                    ->andWhere('tag_id = '.$tag_id)
                    ->execute();
            $ins = Doctrine_Core::getTable('TagPost')->create(array('post_id' => '0', 'tag_id' => $post_id));
        }
    }
    
}
