<?php

/**
 * PostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Post');
    }
    
    public function getPostSearch($text)
    {
        
        $text = str_replace('\'', '', $text);
        $arrtext = explode(" ",preg_replace("/(\s){2,}/", " ", trim($text)));
        if($arrtext[0] == '')
            {return $this->getRecordInstance();}
        $like = "";
        foreach ($arrtext as $value)
        {
            $like .= "OR p.content_path1 LIKE '%".$value."%' OR p.content_path2 LIKE '%".$value."%'";
        }
        $like = substr($like, 3);
        $q = $this->createQuery('p')->where($like)->orderBy('p.created_at DESC');
        
        return $q->execute();
    }
    
    public function getPostsForTag($id_tag)
    {
        $q = $this->createQuery('p')
             ->leftJoin('p.TagPost tp')   
             ->where('tp.tag_id = ?', $id_tag)
             ->andWhere('p.id = tp.post_id')
             ->orderBy('p.created_at DESC');
        
        return $q;
    }
    
}