<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Post extends BasePost
{
    
    public function getTagsPost($id_post)
    {
        $q = Doctrine_Query::create()
                ->from('Tag t')
                ->where('t.post_id = ?', $id_post);
 
        return $q->execute();
    }
    
    public function getCountComment($id_post)
    {
        $q = Doctrine_Query::create()
                ->select('count(t.id) as countcomments')
                ->from('Tag t')
                ->where('t.post_id = ?', $id_post);
 
        return $q->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    }
    
    public static function getPopularPosts()
    {
        $q = Doctrine_Query::create()
                ->select('title')
                ->from('Post p')
                ->orderBy('rating DESC')
                ->limit('0, 10');
 
        return $q->execute();
    }
    
}
