<?php

/**
 * PostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Post');
    }
    
    public function getPostsForTag($id_tag)
    {
        $q = $this->createQuery('p')
             ->leftJoin('p.TagPost tp')   
             ->where('tp.tag_id = ?', $id_tag)
             ->andWhere('p.id = tp.post_id')
             ->orderBy('p.created_at DESC');
        
        return $q;
    }
}