<?php

/**
 * TagPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagPost');
    }
}