generator:
  class: sfDoctrineGenerator
  param:
    model_class:           post
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          post
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title: { label: Заголовок }
        rating: { label: Рейтинг }
        created_at: { label: Создано }
        updated_at: { label: Обновлено }
        content_path1: { label: Контен 1 }
        content_path2: { label: Контен 2 }
        tags : { label: Тэги }
      list:
        title: Управление постами
        display: [id, =title, rating, updated_at]
        max_per_page: 5
        sort: [updated_at, desc]
        object_actions:
          _edit:      ~
          _delete:    ~
          comments:
            { label: Комментарии }
      filter:
        display: [title, created_at, updated_at]
      form:
        display: [title, content_path1, content_path2, rating, tags]
      edit:
        title: Редактировать пост <br>"%%title%%"
        display: [title, content_path1, content_path2, rating, tags]
      new:
        title: Создать пост
        display: [title, content_path1, content_path2, rating, tags]