generator:
  class: sfDoctrineGenerator
  param:
    model_class:           post
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          post
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title: { label: Заголовок }
        rating: { label: Рейтинг }
        created_at: { label: Создано }
        updated_at: { label: Обновлено }
        content_path1: { label: Контен 1 }
        content_path2: { label: Контен 2 }
        
      list:
        title: Управление постами
        display: [id, =title, rating, updated_at]
        max_per_page: 5
        sort: [updated_at, desc]
      filter:
        display: [title, created_at, updated_at]
      form:    ~
      edit:
        title: Редактировать пост "%%title%%"
      new:
        title: Создать пост
