generator:
  class: sfDoctrineGenerator
  param:
    model_class:           post
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          post
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: Управление постами
        display: [id, =title, rating, updated_at]
        fields:
          title: { name: заголовок }
          rating: { name: рейтинг }
          updated_at: { name: обновлено }
        max_per_page: 5
        sort: [updated_at, desc]
      filter:  ~
      form:    ~
      edit:
        title: Редактировать пост "%%title%%"
      new:
        title: Создать пост
