generator:
  class: sfDoctrineGenerator
  param:
    model_class:           comment
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          comment
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        listofpost:
          title: Управление комментариями     
      fields:  ~
      list:
        display: [text, created_at, updated_at]
        sort: [updated_at, desc]
      filter:
        display: [text, created_at, updated_at]
      form:    ~
      edit:    ~
      new:     ~
