Post:
  actAs: { Timestampable: ~ }
  columns:
    title:          { type: string(255), notnull: true }
    content_path1:  { type: string(1024), notnull: true }
    content_path2:  { type: string(10240), notnull: true }
    rating:         { type: integer, notnull: true, default: 0 }

Tag:
  columns:
    word: { type: string(128), notnull: true }

TagPost:
  columns:
    post_id: { type: integer, notnull: true }
    tag_id: { type: integer, notnull: true }
  relations:
    Post: { onDelete: CASCADE, local: post_id, foreign: id }
    Tag: { onDelete: CASCADE, local: tag_id, foreign: id }
    
Comment:
  actAs: { Timestampable: ~ }
  columns:
    post_id: { type: integer, notnull: true }
    sf_guard_user_id: { type: integer, notnull: true }
    text: { type: string(1024), notnull: true }
  relations:
    Post: { onDelete: CASCADE, local: post_id, foreign: id }
    sfGuardUser: { onDelete: CASCADE, local: sf_guard_user_id, foreign: id }
    
Page:
  columns:
    name: { type: string(32), notnull: true }
    title: { type: string(32), notnull: true }
    content:  { type: string(10240), notnull: true }